"""
Trading Journal With Voice — Setup / Install Script

Run this once to:
  1. Create .env from template if missing
  2. Install Python dependencies
  3. Check for external tools (Whisper.cpp, Ollama)
  4. Create necessary directories
  5. Initialize database (via backend)

Usage:
    python setup.py           # interactive setup
    python setup.py --quick   # quick setup (defaults only)
"""

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent


def print_step(msg: str):
    print(f"\n{'='*60}")
    print(f"  {msg}")
    print(f"{'='*60}")


def check_python():
    """Check Python version."""
    print_step("Checking Python version")
    v = sys.version_info
    if v.major < 3 or (v.major == 3 and v.minor < 10):
        print(f"  ❌ Python 3.10+ required. You have {v.major}.{v.minor}.{v.micro}")
        return False
    print(f"  ✅ Python {v.major}.{v.minor}.{v.micro}")


def create_env():
    """Create .env file from template if it doesn't exist."""
    print_step("Environment configuration")
    env_path = PROJECT_ROOT / ".env"
    env_example = PROJECT_ROOT / "config" / ".env.example"

    if env_path.exists():
        print("  ✅ .env already exists")
        return

    # Create example env
    env_content = """# Trading Journal — Environment Variables
# Copy this to .env and fill in your keys

# --- Backend ---
DATABASE_URL=sqlite:///./trading_journal.db
CORS_ORIGINS=http://localhost:5173,http://localhost:3000

# --- Broker API Keys ---
# Alpaca (free stocks/crypto)
# ALPACA_API_KEY=
# ALPACA_SECRET_KEY=

# Interactive Brokers (requires TWS/Gateway running)
# IBKR_HOST=127.0.0.1
# IBKR_PORT=7497

# cTrader (free forex)
# CTRADER_CLIENT_ID=
# CTRADER_CLIENT_SECRET=

# Charles Schwab
# SCHWAB_APP_KEY=
# SCHWAB_APP_SECRET=

# --- AI ---
# Ollama runs locally (no key needed)
# OLLAMA_URL=http://localhost:11434

# Gemini API (free tier, 60 req/min)
# GEMINI_API_KEY=
"""
    if env_example.exists():
        shutil.copy2(env_example, env_path)
        print("  ✅ Created .env from config/.env.example")
    else:
        env_path.write_text(env_content)
        print("  ✅ Created .env with default values")
        print("  ⚠️  Edit .env to add your API keys")

    # Also create config/.env.example
    if not env_example.exists():
        env_example.parent.mkdir(parents=True, exist_ok=True)
        env_example.write_text(env_content)


def install_deps():
    """Install Python dependencies from requirements files."""
    print_step("Installing Python dependencies")

    requirements = [
        ("Core", [
            "fastapi>=0.111.0", "uvicorn[standard]>=0.30.0",
            "sqlalchemy>=2.0.31", "pydantic-settings>=2.3.0",
            "python-multipart>=0.0.9", "aiofiles>=24.1.0",
            "requests>=2.31.0", "pyyaml>=6.0",
            "httpx>=0.27.0",
        ]),
        ("Analytics", [
            "duckdb>=1.0.0",
        ]),
        ("Broker APIs", [
            "alpaca-py>=0.30.0",  # Alpaca
            "ib_insync>=0.9.86",  # IBKR
        ]),
        ("Screenshots", [
            "mss>=9.0.0", "pillow>=10.0.0", "pynput>=1.7.0",
        ]),
        ("Voice", [
            # pyaudio for recording (platform-dependent)
        ]),
        ("AI", [
            "httpx>=0.27.0",  # For Ollama API calls
        ]),
    ]

    for name, pkgs in requirements:
        if pkgs:
            print(f"  Installing {name}...")
            try:
                subprocess.run(
                    [sys.executable, "-m", "pip", "install"] + pkgs,
                    capture_output=True, text=True, timeout=120,
                )
                print(f"    ✅ {name} done")
            except subprocess.TimeoutExpired:
                print(f"    ⚠️  {name} timed out. Run manually: pip install {' '.join(pkgs)}")
            except Exception as e:
                print(f"    ⚠️  {name} failed: {e}")

    # venv requirements.txt
    req_file = PROJECT_ROOT / "requirements.txt"
    req_lines = [
        "# Trading Journal — All Dependencies",
        "# Generated by setup.py",
        "",
        "fastapi>=0.111.0",
        "uvicorn[standard]>=0.30.0",
        "sqlalchemy>=2.0.31",
        "pydantic-settings>=2.3.0",
        "python-multipart>=0.0.9",
        "aiofiles>=24.1.0",
        "httpx>=0.27.0",
        "requests>=2.31.0",
        "pyyaml>=6.0",
        "duckdb>=1.0.0",
        "alpaca-py>=0.30.0",
        "mss>=9.0.0",
        "pillow>=10.0.0",
        "pynput>=1.7.6",
    ]
    if not req_file.exists():
        req_file.write_text("\n".join(req_lines) + "\n")
        print("  ✅ Created requirements.txt")


def check_external_tools():
    """Check for external dependencies (Whisper.cpp, Ollama)."""
    print_step("External tools check")

    tools = {
        "Ollama": {
            "cmd": ["ollama", "--version"] if os.name != "nt" else ["ollama.exe", "--version"],
            "url": "https://ollama.com/download",
            "optional": True,
        },
        "Whisper.cpp": {
            "cmd": ["whisper-cli"] if os.name != "nt" else ["whisper-cli.exe"],
            "url": "https://github.com/ggerganov/whisper.cpp",
            "optional": True,
        },
    }

    for name, info in tools.items():
        try:
            result = subprocess.run(
                info["cmd"], capture_output=True, text=True, timeout=10,
            )
            if result.returncode == 0 or result.returncode == 1:  # some tools return 1 for --version
                print(f"  ✅ {name} found")
            else:
                raise FileNotFoundError
        except (FileNotFoundError, subprocess.TimeoutExpired):
            if info["optional"]:
                print(f"  ⚠️  {name} not found (optional)")
                print(f"     Get it at: {info['url']}")
            else:
                print(f"  ❌ {name} not found. Install: {info['url']}")


def create_directories():
    """Create required directories."""
    print_step("Creating directories")
    dirs = [
        "screenshots",
        "voice_recordings",
        "exports/csv",
        "exports/parquet",
        "analytics",
        "config",
        "logs",
        "uploads",
    ]
    for d in dirs:
        (PROJECT_ROOT / d).mkdir(parents=True, exist_ok=True)
    print(f"  ✅ Created {len(dirs)} directories")


def init_database():
    """Initialize the SQLite database by running the backend once."""
    print_step("Database initialization")
    db_path = PROJECT_ROOT / "trading_journal.db"
    if db_path.exists():
        print(f"  ✅ Database exists ({db_path.stat().st_size / 1024:.0f} KB)")
        return

    # Try to start the backend briefly to create tables
    print("  Starting backend to initialize database...")
    try:
        subprocess.run(
            [sys.executable, str(PROJECT_ROOT / "backend" / "run.py")],
            cwd=str(PROJECT_ROOT),
            timeout=5,
        )
    except subprocess.TimeoutExpired:
        # The backend runs indefinitely — timeout is expected
        pass
    except Exception as e:
        print(f"  ⚠️  Could not auto-init database: {e}")
        print("  Run 'python backend/run.py' manually after setup")


def print_summary():
    """Print setup summary."""
    print_step("Setup Complete")
    print("""
  Trading Journal With Voice is ready!

  Quick start:
    python start_journal.py     # Launch everything
    python journal_cli.py --help  # CLI commands

  Or run components separately:
    backend/run.py               # FastAPI server (port 8000)
    python journal_cli.py ui     # Start frontend dev server (port 5173)

  Documentation:
    docs/                        # Setup and usage guides
    prompts/                     # Research and design docs
    RESTART_INSTRUCTION.md       # Project restart context

  Existing data preserved:
    - trading_journal.db         (your SQLite database)
    - research/                  (TradeViz and other research)
    - prompts/                   (Kimi research results)
    - trading_notes/             (existing notes)
    - screenshots/               (existing captures)

  First-time setup:
    1. Edit .env to add your broker API keys
    2. Run `ollama pull qwen3:8b` for AI analysis
    3. Install Whisper.cpp for voice input
    4. Browse to http://localhost:8000
""")


def main():
    parser = argparse.ArgumentParser(description="Trading Journal Setup")
    parser.add_argument("--quick", action="store_true", help="Quick setup (skip optional checks)")
    args = parser.parse_args()

    print("""
  ╔══════════════════════════════════════════════╗
  ║    Trading Journal With Voice — Setup        ║
  ║    Free · Local-first · AI-powered           ║
  ╚══════════════════════════════════════════════╝
    """)

    check_python()
    create_env()
    create_directories()
    install_deps()

    if not args.quick:
        check_external_tools()

    init_database()
    print_summary()


if __name__ == "__main__":
    main()
